# Copy dos criativos estáticos do Ebook Olheiras: PT (OCR limpo) -> ES LatAm.
# Cada item: (id, arquivos Brasil, [(pt, es), ...], notas)
P="[PRECIO]"; PA="[PRECIO ANTERIOR]"
T="Relleno tridimensional de ojeras: una guía completa con la metodología ARTI"
C=[
("Ads 01 (Feed e Story, png)", "Ads 01 - PTO - Feed.png · Ads 01 - PTO - Story.png", [
 ("76% DE DESCONTO PARA INJETORES", f"[X] % DE DESCUENTO PARA INYECTORES"),
 ("DOMINAREM O PROCEDIMENTO MAIS DESAFIADOR DA HARMONIZAÇÃO FACIAL (O PREENCHIMENTO DE OLHEIRAS) E SE TORNAREM REFERÊNCIA NO MERCADO.", "QUE QUIEREN DOMINAR EL PROCEDIMIENTO MÁS DESAFIANTE DE LA ARMONIZACIÓN FACIAL (EL RELLENO DE OJERAS) Y CONVERTIRSE EN REFERENTES DEL MERCADO."),
 ("TOQUE EM SAIBA MAIS", "TOQUE EN MÁS INFORMACIÓN")],
 "O percentual de desconto depende do preço LATAM (pendente). O OCR leu só parte da primeira linha; conferir na arte se há o verbo 'dominarem'."),
("Ads 02 (Feed e Story, png)", "Ads 02 - PTO - Feed.png · Ads 02 - PTO - Story.png", [
 ("Faça uma pergunta", "Haga una pregunta"),
 ("Dr. João, preenchimento de olheiras é o meu pesadelo. O que fazer?", "Dr. João, el relleno de ojeras es mi pesadilla. ¿Qué hago?"),
 ("Injetor, o preenchimento de olheiras é um dos procedimentos mais desafiadores e lucrativos da harmonização facial.", "Estimado inyector: el relleno de ojeras es uno de los procedimientos más desafiantes y rentables de la armonización facial."),
 ("Sou o Dr. João Pithon, médico, pesquisador e co-autor do livro Arquitetura Facial. Se tem alguém que pode te mostrar como dominar essa região de forma segura e previsível, sou eu.", "Soy el Dr. João Pithon, médico, investigador y coautor del libro Arquitetura Facial. Si hay alguien que pueda mostrarle cómo dominar esta región de forma segura y previsible, soy yo."),
 ("Por um valor simbólico, apenas R$ 97,00, você terá acesso ao meu eBook: Preenchimento Tridimensional de Olheiras: Um Guia Completo com a Metodologia ARTI", f"Por un valor simbólico, solo {P}, tendrá acceso a mi ebook {T}."),
 ("Toque em SAIBA MAIS e garanta o seu!", "Toque en MÁS INFORMACIÓN y asegure el suyo.")],
 "Título do livro do autor (Arquitetura Facial) mantido em português: nome próprio de obra."),
("Ads 03 (Feed e Story, png)", "Ads 03 - PTO - Feed.png · Ads 03 - PTO - Story.png", [
 ("Aprenda o preenchimento tridimensional de olheiras", "Aprenda el relleno tridimensional de ojeras"),
 ("Este guia revela como aplicar a metodologia ARTI (Anatomia, Reologia, Técnica e Intercorrências) no preenchimento de olheiras, a região mais delicada da face, conquistando resultados superiores onde a maioria falha.", "Esta guía muestra cómo aplicar la metodología ARTI (Anatomía, Reología, Técnica e Intercurrencias) en el relleno de ojeras, la región más delicada del rostro, para obtener resultados superiores donde la mayoría falla."),
 ("De R$200,00 Por apenas R$ 97,00", f"De {PA} a solo {P}"),
 ("CLIQUE E GARANTA O SEU DESCONTO", "HAGA CLIC Y ASEGURE SU DESCUENTO")], ""),
("Ads 04 (Feed e Story, png)", "Ads 04 - PTO - Feed.png · Ads 04 - PTO - Story.png", [
 ("Hoje, saber fazer o preenchimento dessa região é algo que diferencia a maior parte dos injetores de todo o mundo, não somente do Brasil.", "Hoy, saber rellenar esta región es lo que distingue a la mayoría de los inyectores en todo el mundo, no solo en Brasil."),
 ("Esta é uma oportunidade imperdível, onde você irá melhorar os seus resultados de maneira efetiva e segura.", "Es una oportunidad única para mejorar sus resultados de manera eficaz y segura."),
 ("eBook: Preenchimento Tridimensional de Olheiras: Um Guia Completo com a Metodologia ARTI", f"Ebook: {T}"),
 ("Este guia revela como aplicar a metodologia ARTI (Anatomia, Reologia, Técnica e Intercorrências) no preenchimento de olheiras, a região mais delicada da face, conquistando resultados superiores onde a maioria falha.", "Esta guía muestra cómo aplicar la metodología ARTI (Anatomía, Reología, Técnica e Intercurrencias) en el relleno de ojeras, la región más delicada del rostro, para obtener resultados superiores donde la mayoría falla."),
 ("Toque em “Saiba mais” e libere o seu acesso!", "Toque en “Más información” y obtenga su acceso.")],
 "O topo da arte tem a palavra INJETORES cortada no OCR (\"NIETORES\"): traduzir como INYECTORES."),
("Ads 05 (Feed e Story, png)", "Ads 05 - PTO - Feed.png · Ads 05 - PTO - Story.png", [
 ("eBook Preenchimento Tridimensional de Olheiras: Um Guia Completo com a Metodologia ARTI", f"Ebook {T}"),
 ("✔ Aprenda o preenchimento tridimensional de olheiras", "✔ Aprenda el relleno tridimensional de ojeras"),
 ("De R$200,00 Por apenas R$ 97,00", f"De {PA} a solo {P}"),
 ("CLIQUE E GARANTA O SEU DESCONTO", "HAGA CLIC Y ASEGURE SU DESCUENTO")], ""),
("Ads 06 (Feed e Story, png)", "Ads 06 - PTO - Feed.png · Ads 06 - PTO - Story.png", [],
 "PENDENTE: o OCR do Drive não leu nenhum texto nesta arte. Transcrever olhando a imagem antes de traduzir."),
("Ads 07 (Feed e Story, png)", "Ads 07 - PTO - Feed.png · Ads 07 - PTO - Story.png", [
 ("PREENCHIMENTO TRIDIMENSIONAL DE OLHEIRAS", "RELLENO TRIDIMENSIONAL DE OJERAS"),
 ("48 horas. Ou menos.", "48 horas. O menos."),
 ("É o tempo que você tem para garantir o seu eBook Preenchimento Tridimensional de Olheiras: Um Guia Completo com a Metodologia ARTI, com desconto!", f"Es el tiempo que tiene para obtener su ebook {T}, con descuento."),
 ("TOQUE EM SAIBA MAIS E LIBERE O SEU ACESSO", "TOQUE EN MÁS INFORMACIÓN Y OBTENGA SU ACCESO")],
 "Prazo de 48 horas é urgência: só manter se a oferta LATAM tiver prazo real (regra FEA contra urgência fabricada)."),
("Ads 08 (Feed e Story, png)", "Ads 08 - PTO - Feed.png · Ads 08 - PTO - Story.png", [
 ("PREENCHIMENTO TRIDIMENSIONAL DE OLHEIRAS", "RELLENO TRIDIMENSIONAL DE OJERAS"),
 ("DE R$ 200 POR R$ 97,00", f"DE {PA} A {P}"),
 ("Domine o procedimento mais desafiador da harmonização facial (o preenchimento de olheiras) com a metodologia ARTI, e alcance resultados naturais, seguros e duradouros.", "Domine el procedimiento más desafiante de la armonización facial (el relleno de ojeras) con la metodología ARTI y logre resultados naturales, seguros y duraderos."),
 ("Este guia revela como aplicar a metodologia ARTI (Anatomia, Reologia, Técnica e Intercorrências) no preenchimento de olheiras, a região mais delicada da face, conquistando resultados superiores onde a maioria falha.", "Esta guía muestra cómo aplicar la metodología ARTI (Anatomía, Reología, Técnica e Intercurrencias) en el relleno de ojeras, la región más delicada del rostro, para obtener resultados superiores donde la mayoría falla."),
 ("Toque em SAIBA MAIS e garanta o seu desconto", "Toque en MÁS INFORMACIÓN y asegure su descuento")], ""),
("Ads 09 (Feed e Story, png)", "Ads 09 - PTO - Feed.png · Ads 09 - PTO - Story.png", [],
 "PENDENTE: o OCR do Drive não leu nenhum texto nesta arte. Transcrever olhando a imagem antes de traduzir."),
("Ads 10 (Feed e Story, png)", "Ads 10 - PTO - Feed.png · Ads 10 - PTO - Story.png", [
 ("Aprenda o preenchimento tridimensional de olheiras ao dominar:", "Aprenda el relleno tridimensional de ojeras dominando:"),
 ("1. Técnicas de injeção", "1. Técnicas de inyección"),
 ("2. Regiões de risco", "2. Zonas de riesgo"),
 ("3. Plano anatômico correto", "3. Plano anatómico correcto"),
 ("CLIQUE E GARANTA O SEU DESCONTO", "HAGA CLIC Y ASEGURE SU DESCUENTO")], ""),
("Ads 11 (Feed e Story, png)", "Ads 11 - PTO - Feed.png · Ads 11 - PTO - Story.png", [
 ("De R$200,00 por apenas R$ 97,00", f"De {PA} a solo {P}"),
 ("Aprenda o preenchimento tridimensional de olheiras ao dominar:", "Aprenda el relleno tridimensional de ojeras dominando:"),
 ("1. Técnicas de injeção", "1. Técnicas de inyección"),
 ("2. Regiões de risco", "2. Zonas de riesgo"),
 ("3. Plano anatômico correto", "3. Plano anatómico correcto"),
 ("CLIQUE E GARANTA O SEU DESCONTO", "HAGA CLIC Y ASEGURE SU DESCUENTO")], ""),
("Ads 12 (Feed e Story, png)", "Ads 12 - PTO - Feed.png · Ads 12 - PTO - Story.png", [
 ("Preenchimento Tridimensional de Olheiras: Um Guia Completo com a Metodologia ARTI", T),
 ("Este guia revela como aplicar a metodologia ARTI (Anatomia, Reologia, Técnica e Intercorrências) no preenchimento de olheiras, a região mais delicada da face, conquistando resultados superiores onde a maioria falha.", "Esta guía muestra cómo aplicar la metodología ARTI (Anatomía, Reología, Técnica e Intercurrencias) en el relleno de ojeras, la región más delicada del rostro, para obtener resultados superiores donde la mayoría falla."),
 ("Toque em “Saiba mais” e libere o seu acesso!", "Toque en “Más información” y obtenga su acceso.")], ""),
("Ads 13 (Feed e Story, png)", "Ads 13- PTO - Feed.png · Ads 13 - PTO - Story.png", [
 ("PREENCHIMENTO TRIDIMENSIONAL DE OLHEIRAS", "RELLENO TRIDIMENSIONAL DE OJERAS"),
 ("O PASSO A PASSO para injetores dominarem o preenchimento tridimensional de olheiras, mesmo começando do zero!", "EL PASO A PASO para que los inyectores dominen el relleno tridimensional de ojeras, incluso si empiezan desde cero."),
 ("Este guia revela como aplicar a metodologia ARTI (Anatomia, Reologia, Técnica e Intercorrências) no preenchimento de olheiras, a região mais delicada da face, conquistando resultados superiores onde a maioria falha.", "Esta guía muestra cómo aplicar la metodología ARTI (Anatomía, Reología, Técnica e Intercurrencias) en el relleno de ojeras, la región más delicada del rostro, para obtener resultados superiores donde la mayoría falla."),
 ("De R$200,00 Por apenas R$ 97,00 SÓ HOJE", f"De {PA} a solo {P} SOLO HOY"),
 ("CLIQUE E GARANTA O SEU DESCONTO", "HAGA CLIC Y ASEGURE SU DESCUENTO")],
 "\"SÓ HOJE\" é urgência: manter só se a oferta LATAM tiver prazo real. A capa do ebook dentro da arte (mockup) segue em português: trocar pela capa ES."),
("Ads 14 (Feed e Story, png)", "Ads 14 - PTO - Feed.png · Ads 14 - PTO - Story.png", [
 ("PREENCHIMENTO TRIDIMENSIONAL DE OLHEIRAS", "RELLENO TRIDIMENSIONAL DE OJERAS"),
 ("Tem medo de realizar o procedimento mais desafiador da harmonização facial: o preenchimento de olheiras?", "¿Le da miedo realizar el procedimiento más desafiante de la armonización facial: el relleno de ojeras?"),
 ("Este guia foi criado justamente para evitar isso: domine o procedimento mais desafiador da harmonização facial com a metodologia ARTI e alcance resultados naturais, seguros e duradouros.", "Esta guía se creó precisamente para evitarlo: domine el procedimiento más desafiante de la armonización facial con la metodología ARTI y logre resultados naturales, seguros y duraderos."),
 ("De R$200,00 Por apenas R$ 97,00", f"De {PA} a solo {P}"),
 ("Toque em SAIBA MAIS e garanta o seu!", "Toque en MÁS INFORMACIÓN y asegure el suyo.")],
 "Mockup da capa do ebook em português dentro da arte: trocar pela capa ES."),
("Ads 15 (Feed e Story, png)", "Ads 15 - PTO - Feed.png · Ads 15 - PTO - Story.png", [
 ("PREENCHIMENTO TRIDIMENSIONAL DE OLHEIRAS", "RELLENO TRIDIMENSIONAL DE OJERAS"),
 ("Oportunidade única para injetores que desejam dominar o procedimento mais desafiador da harmonização facial (o preenchimento de olheiras) e se tornarem referência no mercado.", "Una oportunidad única para inyectores que quieren dominar el procedimiento más desafiante de la armonización facial (el relleno de ojeras) y convertirse en referentes del mercado."),
 ("eBook: Preenchimento Tridimensional de Olheiras: Um Guia Completo com a Metodologia ARTI + 03 Casos Clínicos Exclusivos", f"Ebook: {T} + 3 casos clínicos exclusivos"),
 ("De R$200,00 Por apenas R$ 97,00 SÓ HOJE", f"De {PA} a solo {P} SOLO HOY"),
 ("Toque em SAIBA MAIS e garanta o seu!", "Toque en MÁS INFORMACIÓN y asegure el suyo.")],
 "\"SÓ HOJE\": mesma ressalva de urgência. Mockup da capa em português: trocar pela capa ES."),
("[FEED] ADS 02 (jpg)", "[FEED] ADS 02.jpg", [
 ("APRENDA O PASSO A PASSO PARA TRATAR OLHEIRAS SEM IMPROVISO.", "APRENDA EL PASO A PASO PARA TRATAR OJERAS SIN IMPROVISAR."),
 ("EBOOK COM PROTOCOLO COMPLETO: ANÁLISE, PLANEJAMENTO E EXECUÇÃO.", "EBOOK CON PROTOCOLO COMPLETO: ANÁLISIS, PLANIFICACIÓN Y EJECUCIÓN."),
 ("Acesso completo por apenas R$97", f"Acceso completo por solo {P}"),
 ("O PRIMEIRO & MAIS VENDIDO · +30 MIL CÓPIAS VENDIDAS", "EL PRIMERO Y MÁS VENDIDO · +30 MIL COPIAS VENDIDAS")],
 "O selo '+30 mil cópias' se refere à edição em português: decidir se mantém no LATAM. A página aberta do ebook no mockup tem texto ilegível (gerado por IA): trocar por página real da edição ES."),
("[STORIES] ADS 01 (jpg)", "[STORIES] ADS 01.jpg", [
 ("Você ainda evita tratar olheiras por medo de complicações?", "¿Todavía evita tratar ojeras por miedo a las complicaciones?"),
 ("Domine a anatomia, profundidade e técnica certa para cada caso.", "Domine la anatomía, la profundidad y la técnica adecuada para cada caso."),
 ("Ebook com marcação, planos de aplicação e escolha correta de produto.", "Ebook con marcación, planos de aplicación y elección correcta del producto."),
 ("De R$297 → por apenas R$97", f"De {PA} → a solo {P}"),
 ("O PRIMEIRO & MAIS VENDIDO · +30 MIL CÓPIAS VENDIDAS", "EL PRIMERO Y MÁS VENDIDO · +30 MIL COPIAS VENDIDAS"),
 ("Toque em Saiba Mais e garanta o seu.", "Toque en Más información y asegure el suyo.")],
 "Mesma ressalva do selo e da página do mockup gerada por IA."),
("[FEED] ADS 03 (jpg)", "[FEED] ADS 03.jpg", [
 ("A região mais temida da face pode virar a mais lucrativa, quando você sabe exatamente onde, quanto e como aplicar.", "La región más temida del rostro puede convertirse en la más rentable cuando usted sabe exactamente dónde, cuánto y cómo aplicar."),
 ("EBOOK COM PONTOS DE APLICAÇÃO, VOLUMES E VARIAÇÕES POR TIPO DE OLHEIRA.", "EBOOK CON PUNTOS DE APLICACIÓN, VOLÚMENES Y VARIACIONES SEGÚN EL TIPO DE OJERA."),
 ("De R$297 por apenas R$97", f"De {PA} a solo {P}")], ""),
("[FEED] ADS 04 e [STORIES] ADS 04 (jpg)", "[FEED] ADS 04.jpg · [STORIES] ADS 04.jpg", [
 ("Você estudou... mas na hora de aplicar, trava?", "Usted estudió… pero, a la hora de aplicar, ¿se bloquea?"),
 ("Aqui você aprende o que realmente importa: execução segura.", "Aquí aprende lo que realmente importa: una ejecución segura."),
 ("EBOOK COM DEMONSTRAÇÃO PRÁTICA E DECISÕES CLÍNICAS EXPLICADAS.", "EBOOK CON DEMOSTRACIÓN PRÁCTICA Y DECISIONES CLÍNICAS EXPLICADAS.")], ""),
("[FEED] ADS 05 e [STORIES] ADS 05 (jpg)", "[FEED] ADS 05.jpg · [STORIES] ADS 05.jpg", [
 ("Compartilhando esse caso de olheiras + lábios seguindo os ensinamentos do Prof. Muito feliz com o resultado", "Comparto este caso de ojeras + labios siguiendo las enseñanzas del profesor. Muy feliz con el resultado."),
 ("Só queria mostrar a olheira que saiu agorinha aqui no meu consultório", "Solo quería mostrarle el relleno de ojeras que acabo de realizar en mi consultorio."),
 ("O preenchimento de olheiras não é uma técnica difícil, para quem tem um raciocínio clínico estruturado.", "El relleno de ojeras no es una técnica difícil para quien tiene un razonamiento clínico estructurado."),
 ("Acesso completo por apenas R$97", f"Acceso completo por solo {P}"),
 ("TOQUE EM SAIBA MAIS E GARANTA O SEU.", "TOQUE EN MÁS INFORMACIÓN Y ASEGURE EL SUYO.")],
 "DECIDE O AUTOR: as mensagens são prints de depoimento de alunos brasileiros. Traduzir o print altera um depoimento real; sugestão é manter o print em português com legenda em espanhol, ou trocar por depoimento de aluno hispanohablante. Conferir TCLE das fotos de paciente."),
("[FEED] ADS 06 e [STORIES] ADS 06 (jpg)", "[FEED] ADS 06.jpg · [STORIES] ADS 06.jpg", [
 ("Evitar olheiras está te custando pacientes. Domine uma das áreas mais valorizadas da harmonização.", "Evitar tratar ojeras le está costando pacientes. Domine una de las áreas más valoradas de la armonización."),
 ("Com um ebook que mostra o raciocínio clínico por trás de cada aplicação.", "Con un ebook que muestra el razonamiento clínico detrás de cada aplicación."),
 ("O PRIMEIRO & MAIS VENDIDO · +30 MIL CÓPIAS VENDIDAS", "EL PRIMERO Y MÁS VENDIDO · +30 MIL COPIAS VENDIDAS"),
 ("TOQUE EM SAIBA MAIS E GARANTA O SEU.", "TOQUE EN MÁS INFORMACIÓN Y ASEGURE EL SUYO.")], ""),
("[FEED] ADS 07 e [STORIES] ADS 07 (jpg)", "[FEED] ADS 07.jpg · [STORIES] ADS 07.jpg", [
 ("PREENCHIMENTO TRIDIMENSIONAL DE OLHEIRAS", "RELLENO TRIDIMENSIONAL DE OJERAS"),
 ("Existe um limite seguro e você precisa conhecer: aprenda anatomia aplicada sem achismo e sem risco desnecessário.", "Existe un límite seguro y usted necesita conocerlo: aprenda anatomía aplicada sin suposiciones y sin riesgos innecesarios."),
 ("Ebook com zonas de risco, profundidade e cuidados para evitar complicações.", "Ebook con zonas de riesgo, profundidad y cuidados para evitar complicaciones."),
 ("GARANTA JÁ O SEU", "ASEGURE EL SUYO AHORA")], ""),
("[FEED] ADS 08 e [STORIES] ADS 08 (jpg)", "[FEED] ADS 08.jpg · [STORIES] ADS 08.jpg", [
 ("De insegura para referência em olheiras.", "De insegura a referente en ojeras."),
 ("Com a Técnica Tridimensional de Preenchimento de Olheiras.", "Con la técnica tridimensional de relleno de ojeras."),
 ("Ebook Preenchimento Tridimensional de Olheiras: Um Guia Completo com a Metodologia ARTI", f"Ebook {T}"),
 ("Metodologia ARTI no Preenchimento de Olheiras", "Metodología ARTI en el relleno de ojeras"),
 ("Compartilhando esse caso de olheiras + lábios seguindo os ensinamentos do Prof. Muito feliz com o resultado", "Comparto este caso de ojeras + labios siguiendo las enseñanzas del profesor. Muy feliz con el resultado."),
 ("Só queria mostrar a olheira que saiu agorinha aqui no meu consultório", "Solo quería mostrarle el relleno de ojeras que acabo de realizar en mi consultorio."),
 ("O PRIMEIRO & MAIS VENDIDO · 30 MIL CÓPIAS VENDIDAS", "EL PRIMERO Y MÁS VENDIDO · 30 MIL COPIAS VENDIDAS"),
 ("TOQUE EM SAIBA MAIS E GARANTA O SEU", "TOQUE EN MÁS INFORMACIÓN Y ASEGURE EL SUYO")],
 "Mesma decisão de depoimento do Ads 05. 'Insegura' no feminino espelha o original."),
("[FEED] ADS 09 e [STORIES] ADS 09 (jpg)", "[FEED] ADS 09.jpg · [STORIES] ADS 09.jpg", [
 ("Não é sobre preencher. É sobre saber onde NÃO tocar.", "No se trata de rellenar. Se trata de saber dónde NO tocar."),
 ("Evite erros comuns que comprometem o resultado.", "Evite los errores comunes que comprometen el resultado."),
 ("Ebook com erros mais frequentes e como corrigir na prática.", "Ebook con los errores más frecuentes y cómo corregirlos en la práctica."),
 ("O PRIMEIRO & MAIS VENDIDO · +30 MIL CÓPIAS VENDIDAS", "EL PRIMERO Y MÁS VENDIDO · +30 MIL COPIAS VENDIDAS"),
 ("TOQUE EM SAIBA MAIS E GARANTA O SEU.", "TOQUE EN MÁS INFORMACIÓN Y ASEGURE EL SUYO.")],
 "Página do mockup com texto ilegível (gerado por IA): trocar por página real ES."),
("[FEED] ADS 10 e [STORIES] ADS 10 (jpg)", "[FEED] ADS 10.jpg · [STORIES] ADS 10.jpg", [
 ("Se você ainda depende de tentativa e erro, você está em risco.", "Si todavía depende del ensayo y error, está en riesgo."),
 ("Aprenda um método seguro, replicável e clínico.", "Aprenda un método seguro, replicable y clínico."),
 ("Ebook com passo a passo completo da primeira avaliação ao resultado final.", "Ebook con el paso a paso completo, desde la primera evaluación hasta el resultado final."),
 ("De R$297 por apenas R$97", f"De {PA} a solo {P}"),
 ("TOQUE EM SAIBA MAIS E GARANTA O SEU.", "TOQUE EN MÁS INFORMACIÓN Y ASEGURE EL SUYO.")], ""),
("[FEED] ADS 11 e [STORIES] ADS 11 (jpg)", "[FEED] ADS 11.jpg · [STORIES] ADS 11.jpg", [
 ("De R$297 Por apenas R$97", f"De {PA} a solo {P}"),
 ("Metodologia ARTI aplicada ao preenchimento de olheiras;", "Metodología ARTI aplicada al relleno de ojeras;"),
 ("Técnica tridimensional passo a passo;", "Técnica tridimensional paso a paso;"),
 ("Casos clínicos comentados + videoaulas explicativas;", "Casos clínicos comentados + videoclases explicativas;"),
 ("Tudo organizado para aplicação prática imediata.", "Todo organizado para su aplicación práctica inmediata."),
 ("TOQUE EM SAIBA MAIS E GARANTA O SEU", "TOQUE EN MÁS INFORMACIÓN Y ASEGURE EL SUYO")],
 "As videoaulas do ebook ainda estão em português: só prometer videoclases se as versões ES estiverem prontas."),
("[FEED] ADS 12 e [STORIES] ADS 12 (jpg)", "[FEED] ADS 12.jpg · [STORIES] ADS 12.jpg", [
 ("Preenchimento de olheiras não é difícil. É imprevisível pra quem não tem método.", "El relleno de ojeras no es difícil. Es imprevisible para quien no tiene método."),
 ("EVITE: INSEGURANÇA NO PLANO CORRETO; DÚVIDA NO DIAGNÓSTICO; RESULTADOS INCONSISTENTES.", "EVITE: INSEGURIDAD SOBRE EL PLANO CORRECTO; DUDAS EN EL DIAGNÓSTICO; RESULTADOS INCONSISTENTES."),
 ("Aprenda o raciocínio clínico estruturado por R$97", f"Aprenda el razonamiento clínico estructurado por {P}")], ""),
("[FEED] ADS 13 e [STORIES] ADS 13 (jpg)", "[FEED] ADS 13.jpg · [STORIES] ADS 13.jpg", [
 ("Transforme o preenchimento de olheiras no seu maior diferencial, dominando uma habilidade que poucos profissionais possuem.", "Convierta el relleno de ojeras en su mayor diferencial al dominar una habilidad que pocos profesionales tienen."),
 ("De R$297 por apenas R$97", f"De {PA} a solo {P}"),
 ("GARANTA JÁ O SEU", "ASEGURE EL SUYO AHORA")], ""),
("[FEED] ADS 14 (jpg)", "[FEED] ADS 14.jpg", [
 ("O QUE VOCÊ VAI RECEBER POR R$ 97", f"LO QUE RECIBIRÁ POR {P}"),
 ("Técnica tridimensional passo a passo", "Técnica tridimensional paso a paso"),
 ("Raciocínio clínico estruturado", "Razonamiento clínico estructurado"),
 ("Revisão científica com artigos", "Revisión científica con artículos"),
 ("Casos reais comentados", "Casos reales comentados"),
 ("Conteúdo clínico direto para aplicar já no próximo paciente.", "Contenido clínico directo para aplicar desde el próximo paciente."),
 ("O PRIMEIRO E MAIS VENDIDO · +30 MIL CÓPIAS VENDIDAS", "EL PRIMERO Y MÁS VENDIDO · +30 MIL COPIAS VENDIDAS"),
 ("TOQUE EM SAIBA MAIS E GARANTA O SEU EBOOK.", "TOQUE EN MÁS INFORMACIÓN Y ASEGURE SU EBOOK.")], ""),
("[FEED] ADS 15 e ADS 15_V2 (jpg)", "[FEED] ADS 15.jpg · [FEED] ADS 15_V2.jpg", [
 ("ESSE EBOOK É PRA VOCÊ QUE:", "ESTE EBOOK ES PARA USTED SI:"),
 ("Evita tratar olheiras por insegurança", "Evita tratar ojeras por inseguridad"),
 ("Já faz, mas sem previsibilidade", "Ya lo hace, pero sin previsibilidad"),
 ("Quer reduzir risco e ter mais controle técnico", "Quiere reducir riesgos y tener más control técnico"),
 ("Tudo isso com método estruturado por apenas R$ 97", f"Todo esto con un método estructurado por solo {P}"),
 ("TOQUE EM SAIBA MAIS E GARANTA O SEU.", "TOQUE EN MÁS INFORMACIÓN Y ASEGURE EL SUYO.")],
 "V2 tem a página do mockup com texto ilegível (gerado por IA)."),
("[FEED] ADS 16 (jpg)", "[FEED] ADS 16.jpg", [
 ("ATENÇÃO PROFISSIONAIS DA HARMONIZAÇÃO", "ATENCIÓN, PROFESIONALES DE LA ARMONIZACIÓN"),
 ("Por apenas R$97,00 você recebe:", f"Por solo {P} recibe:"),
 ("Metodologia ARTI aplicada ao preenchimento de olheiras", "Metodología ARTI aplicada al relleno de ojeras"),
 ("Técnica tridimensional passo a passo", "Técnica tridimensional paso a paso"),
 ("Raciocínio clínico estruturado", "Razonamiento clínico estructurado"),
 ("Casos clínicos comentados", "Casos clínicos comentados"),
 ("Videoaulas explicativas", "Videoclases explicativas"),
 ("Tudo claro e organizado para melhorar resultados e aumentar sua segurança ao tratar olheiras sem medo de complicações.", "Todo claro y organizado para mejorar resultados y aumentar su seguridad al tratar ojeras sin miedo a las complicaciones."),
 ("TOQUE EM SAIBA MAIS", "TOQUE EN MÁS INFORMACIÓN")],
 "Original diz 'Metodologia ARTI aplicado' (erro de concordância): corrigido em silêncio no ES. Mesma ressalva das videoclases."),
("[FEED] ADS 17 (jpg)", "[FEED] ADS 17.jpg", [
 ("O guia clínico mais vendido sobre olheiras", "La guía clínica más vendida sobre ojeras"),
 ("Aprenda a técnica tridimensional por apenas R$97", f"Aprenda la técnica tridimensional por solo {P}"),
 ("Transforme o preenchimento de olheiras no seu maior diferencial dentro da harmonização facial.", "Convierta el relleno de ojeras en su mayor diferencial dentro de la armonización facial."),
 ("Método comprovado para atuar com precisão anatômica e previsibilidade real.", "Un método probado para trabajar con precisión anatómica y previsibilidad real."),
 ("O PRIMEIRO & MAIS VENDIDO · +30 MIL CÓPIAS VENDIDAS", "EL PRIMERO Y MÁS VENDIDO · +30 MIL COPIAS VENDIDAS"),
 ("TOQUE EM SAIBA MAIS", "TOQUE EN MÁS INFORMACIÓN")], ""),
("[FEED] ADS 18 e [STORIES] ADS 18 (jpg)", "[FEED] ADS 18.jpg · [STORIES] ADS 18.jpg", [
 ("EXCLUSIVO", "EXCLUSIVO"),
 ("Nenhum outro lugar no Brasil ensina esse método.", "Ningún otro lugar de Brasil enseña este método."),
 ("É difícil dominar olheiras, quando ninguém te dá um protocolo clínico para seguir. Por isso, poucos dominam essa técnica.", "Es difícil dominar las ojeras cuando nadie le da un protocolo clínico para seguir. Por eso, pocos dominan esta técnica."),
 ("Você tem duas opções: Continuar evitando olheiras por medo; Ou pagar apenas R$97 pra aprender a mapear e tratar com segurança.", f"Tiene dos opciones: seguir evitando tratar ojeras por miedo, o pagar solo {P} para aprender a mapearlas y tratarlas con seguridad."),
 ("Ebook prático com passos em 3D, casos reais e aplicações comentadas.", "Ebook práctico con pasos en 3D, casos reales y aplicaciones comentadas."),
 ("O PRIMEIRO · +30 MIL CÓPIAS VENDIDAS", "EL PRIMERO · +30 MIL COPIAS VENDIDAS")],
 "DECIDE O AUTOR: a exclusividade 'no Brasil' não serve para o público LATAM, e afirmar 'en Latinoamérica' exige comprovação. Sugestão: 'Un método exclusivo del Dr. João Pithon.'"),
("[FEED] ADS 19 (jpg)", "[FEED] ADS 19.jpg", [
 ("+ de 30 mil cópias vendidas", "Más de 30 mil copias vendidas"),
 ("Seja referência em olheiras por R$97", f"Conviértase en referente en ojeras por {P}"),
 ("Transforme essa área complicada em um grande diferencial na Harmonização Facial", "Convierta esta área complicada en un gran diferencial en la armonización facial"),
 ("Casos reais analisados", "Casos reales analizados"),
 ("SAIBA MAIS SOBRE ESSE MÉTODO", "CONOZCA MÁS SOBRE ESTE MÉTODO")], ""),
("[FEED] ADS 20 e [STORIES] ADS 20 (jpg)", "[FEED] ADS 20.jpg · [STORIES] ADS 20.jpg", [
 ("Você não evita olheiras por falta de técnica, você evita porque sabe o risco que está correndo.", "Usted no evita tratar ojeras por falta de técnica: lo evita porque conoce el riesgo que corre."),
 ("Aprenda a decidir com segurança: profundidade, plano e quantidade (sem improviso).", "Aprenda a decidir con seguridad: profundidad, plano y cantidad (sin improvisar)."),
 ("De R$297 por apenas R$97", f"De {PA} a solo {P}"),
 ("O PRIMEIRO & MAIS VENDIDO · 30 MIL CÓPIAS VENDIDAS", "EL PRIMERO Y MÁS VENDIDO · 30 MIL COPIAS VENDIDAS"),
 ("Toque em Saiba Mais e garanta o seu.", "Toque en Más información y asegure el suyo.")], ""),
("Ads 31 (Feed e Story, png)", "Ads 31 Feed - PTO.png · Ads 31 Story - PTO.png", [
 ("Você não evita olheiras por falta de curso.", "Usted no evita tratar ojeras por falta de cursos."),
 ("Você evita porque ainda não sabe: Qual plano usar · Qual produto escolher · Quando NÃO preencher", "Lo evita porque aún no sabe: qué plano usar · qué producto elegir · cuándo NO rellenar"),
 ("COPIE O PROTOCOLO TRIDIMENSIONAL", "COPIE EL PROTOCOLO TRIDIMENSIONAL"),
 ("+30 MIL CÓPIAS VENDIDAS", "+30 MIL COPIAS VENDIDAS"),
 ("Clique no botão ou aponte o celular para o QR Code para baixar o e-book", "Haga clic en el botón o apunte el celular al código QR para descargar el ebook")],
 "DECIDE O AUTOR: a arte reproduz a capa de um material de terceiros em inglês com a marca Allergan (\"Facial Structure, Understanding the Face Age\"). Pela regra FEA, marca só com aprovação; capa de terceiros não se traduz. QR Code aponta para destino em português: regerar quando houver destino ES."),
("Ads 32 (Feed e Story, png)", "Ads 32 Feed - PTO.png · Ads 32 Story - PTO.png", [
 ("+30 MIL CÓPIAS VENDIDAS", "+30 MIL COPIAS VENDIDAS"),
 ("Tem profissional cobrando menos... e ainda pegando mais pacientes.", "Hay profesionales que cobran menos… y aun así atienden a más pacientes."),
 ("A diferença está na previsibilidade.", "La diferencia está en la previsibilidad."),
 ("QUERO AUMENTAR MINHA PREVISIBILIDADE", "QUIERO AUMENTAR MI PREVISIBILIDAD")], ""),
("Ads 33 (Feed e Story, png)", "Ads 33 Feed - PTO.png · Ads 33 Story - PTO.png", [
 ("Você estudou... mas na hora de aplicar, trava?", "Usted estudió… pero, a la hora de aplicar, ¿se bloquea?"),
 ("Aqui você aprende o que realmente importa:", "Aquí aprende lo que realmente importa:"),
 ("✓ Edema e efeito Tyndall ✓ Regiões de risco ✓ Irregularidades ✓ Bolsas pós preenchimento", "✓ Edema y efecto Tyndall ✓ Zonas de riesgo ✓ Irregularidades ✓ Bolsas tras el relleno"),
 ("QUERO DOMINAR OLHEIRAS", "QUIERO DOMINAR LAS OJERAS")], ""),
("Ads 34 (Feed e Story, png)", "Ads 34 Feed - PTO.png · Ads 34 Story - PTO.png", [
 ("• ACESSO VITALÍCIO", "• ACCESO DE POR VIDA"),
 ("O problema não é preencher olheiras. O problema é usar o produto errado no plano errado.", "El problema no es rellenar ojeras. El problema es usar el producto equivocado en el plano equivocado."),
 ("Copie o protocolo tridimensional que aumenta a previsibilidade e a naturalidade dessa região.", "Copie el protocolo tridimensional que aumenta la previsibilidad y la naturalidad de esta región."),
 ("04. Intercorrências", "04. Intercurrencias"),
 ("+30 MIL CÓPIAS VENDIDAS", "+30 MIL COPIAS VENDIDAS"),
 ("RECEBER ACESSO VITALÍCIO POR R$97", f"OBTENER ACCESO DE POR VIDA POR {P}")],
 "'04. Intercorrências' é o título do capítulo visível no mockup: usar o título do capítulo da edição ES."),
("Ads 35 (Feed e Story, png)", "Ads 35 Feed - PTO.png · Ads 35 Story - PTO.png", [
 ("3 erros que fazem sua olheira ficar artificial", "3 errores que hacen que su relleno de ojeras se vea artificial"),
 ("✗ Produto muito hidrofílico ✗ Plano superficial ✗ Excesso de projeção", "✗ Producto muy hidrofílico ✗ Plano superficial ✗ Exceso de proyección"),
 ("O protocolo tridimensional resolve os 3", "El protocolo tridimensional resuelve los 3"),
 ("QUERO EVITAR ESSES ERROS", "QUIERO EVITAR ESTOS ERRORES")],
 "'Sua olheira' no original é o resultado do preenchimento: explicitado como 'su relleno de ojeras' para não sugerir que a ojera é do leitor."),
("Ads 36 (Feed e Story, png)", "Ads 36 Feed - PTO.png · Ads 36 Story - PTO.png", [
 ("Preenchimento tridimensional de olheiras.", "Relleno tridimensional de ojeras."),
 ("A metodologia ARTI para aumentar previsibilidade, naturalidade e segurança.", "La metodología ARTI para aumentar la previsibilidad, la naturalidad y la seguridad."),
 ("+30 MIL CÓPIAS VENDIDAS", "+30 MIL COPIAS VENDIDAS"),
 ("Assista ao vídeo", "Vea el video"),
 ("Plano anatômico correto · Regiões de risco · Bolus, microbolus e retroinjeção · Escolha do preenchedor ideal", "Plano anatómico correcto · Zonas de riesgo · Bolo, microbolo y retroinyección · Elección del producto de relleno ideal"),
 ("QUERO DOMINAR O PROTOCOLO", "QUIERO DOMINAR EL PROTOCOLO")],
 "A página do mockup tem transcrição de aula em português e QR Code: trocar pela página ES correspondente."),
("Ads 37 (Feed e Story, png)", "Ads 37 Feed - PTO.png · Ads 37 Story - PTO.png", [
 ("Depois de mais de 20 mil alunos... percebemos um padrão.", "Después de más de 20 mil alumnos… notamos un patrón."),
 ("As profissionais com melhores resultados em olheiras:", "Las profesionales con mejores resultados en ojeras:"),
 ("✗ não aplicam mais produto. ✓ aplicam no plano correto.", "✗ no aplican más producto. ✓ lo aplican en el plano correcto."),
 ("+30 MIL CÓPIAS VENDIDAS", "+30 MIL COPIAS VENDIDAS"),
 ("APRENDA O QUE ELAS FAZEM", "APRENDA LO QUE ELLAS HACEN")],
 "Original tem '20 mil alunos' aqui e '30 mil profissionais' no Ads 40: números espelhados; o autor deve confirmar qual vale."),
("Ads 38 (Feed e Story, png)", "Ads 38 Feed - PTO.png · Ads 38 Story - PTO.png", [
 ("Não é mais um curso de olheiras. É um protocolo pronto para copiar na próxima paciente.", "No es otro curso de ojeras. Es un protocolo listo para copiar con su próxima paciente."),
 ("Qual cânula usar · Quando fazer bolus · Onde evitar volume · Como reduzir edema · Produtos e planos ideais", "Qué cánula usar · Cuándo hacer un bolo · Dónde evitar volumen · Cómo reducir el edema · Productos y planos ideales"),
 ("+30 MIL CÓPIAS VENDIDAS", "+30 MIL COPIAS VENDIDAS"),
 ("RECEBER ACESSO IMEDIATO", "OBTENER ACCESO INMEDIATO")], ""),
("Ads 39 (Feed e Story, png)", "Ads 39 Feed - PTO.png · Ads 39 Story - PTO.png", [
 ("A maioria das complicações em olheiras começa aqui.", "La mayoría de las complicaciones en ojeras empieza aquí."),
 ("O ebook mostra exatamente: Onde entrar · Profundidade correta · Produto ideal para cada plano", "El ebook muestra exactamente: dónde entrar · la profundidad correcta · el producto ideal para cada plano"),
 ("VER PROTOCOLO COMPLETO", "VER EL PROTOCOLO COMPLETO")], ""),
("Ads 40 (Feed e Story, png)", "Ads 40 Feed - PTO.png · Ads 40 Story - PTO.png", [
 ("+30 MIL CÓPIAS VENDIDAS", "+30 MIL COPIAS VENDIDAS"),
 ("• OFERTA LIMITADA", "• OFERTA LIMITADA"),
 ("Acesso vitalício por apenas R$ 97,00", f"Acceso de por vida por solo {P}"),
 ("Copie o protocolo tridimensional de olheiras utilizado por mais de 30 mil profissionais.", "Copie el protocolo tridimensional de ojeras que utilizan más de 30 mil profesionales."),
 ("GARANTIR MEU ACESSO AGORA", "QUIERO MI ACCESO AHORA")],
 "'Oferta limitada' só se a oferta LATAM tiver limite real."),
]
